services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bai-frontend
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      # SINTAXIS DINÁMICA: ${VARIABLE:-VALOR_POR_DEFECTO}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_N8N_URL=${NEXT_PUBLIC_N8N_URL:-http://localhost:5678}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bai

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bai-backend
    env_file:
      # Esto carga la SECRET_KEY, GOOGLE_API_KEY y BRAVE_API_KEY desde tu archivo
      - ./backend/.env
    environment:
      # Forzamos la conexión a la DB aquí por si falla en el .env
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/bai
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - bai

  db:
    image: postgres:15-alpine
    container_name: bai-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bai
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bai

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: bai-n8n
    restart: always
    environment:
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Madrid # Opcional: Para que los logs salgan con tu hora
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - bai

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - bai

volumes:
  db-data:
  n8n_data:
  caddy_data:
  caddy_config:

networks:
  bai:
    driver: bridge
    